{
 "title": "First",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Host memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "windows_memory_available_bytes / windows_cs_physical_memory_bytes * 100"
    }
   ]
  },
  {
   "title": "Host Network Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "windows_net_current_bandwidth_bytes"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(windows_cpu_time_total{mode!=\"idle\"}[5m])) by (core) * 100"
    }
   ]
  }
 ]
}